import streamlit as st
import pandas as pd
import openpyxl
import re
import time
import io

# List of valid modules (Add all modules here)
VALID_MODULES = [
    "ABRASIVE CLEANING PADS METAL BASED", "ADHESIVE TAPE", "AFTERSHAVE - MALE", "AFTERSUN", "AIR FRESHENERS - SPECIAL APPLICATION", "AIR FRESHENERS CONTINUOUS", "AIR FRESHENERS INSTANT", "ALCOHOL TESTS", "ALCOHOLIC PRE-MIXED DRINKS", "ALLERGY/HAYFEVER REMEDIES", "ALUMINIUM FOIL BAKING CUPS", "ALUMINIUM FOIL CONTAINERS", "ALUMINIUM FOIL ROLLS", "ALUMINIUM FOIL SHEETS", "ANAESTHETIC PRODUCTS", "ANIMAL BITE TREATMENT KIT", "ANIMAL DERIVED HEALTH SUPPLEMENTS", "ANIS/OUZO/PASTIS/ANISEED SPIRITS", "ANTACIDS", "ANTI ALCOHOLISM/NARCOTIC DEPENDENCE - LIQUID", "ANTI BALDNESS REMEDIES", "ANTI DEPRESSANT PRODUCTS", "ANTI HAEMORRHOIDS", "ANTI ITCH/SKIN ALLERGY REMEDIES", "ANTI PARKINSON PRODUCTS", "ANTI SMOKING - ARTIFICIAL CIGARETTES/INHALATORS", "ANTI SMOKING - DEVICE/COMPUTER", "ANTI SMOKING - GUM/LOZENGES/STRIPS/TABLETS", "ANTI SMOKING - LIQUID", "ANTI SMOKING - MAGNETS", "ANTI SMOKING - PATCHES/PLASTERS", "ANTI SNORE TREATMENTS", "ANTI SPASMODICS", "ANTI SPOT/ACNE MEDICATION", "ANTI ULCERANTS", "ANTI VARICOSE VEIN TREATMENTS", "ANTI WART/VERRUCA TREATMENTS", "ANTIBIOTICS - GENERAL PURPOSE", "ANTIFLATULENTS", "ANTIFUNGALS", "ANTINEOPLASTIC AGENTS", "ANTISEPTIC CREAM/LIQUID", "ANTISEPTIC POWDER", "ANTISEPTIC TABLETS", "ANTISEPTIC WIPES", "APERITIFS", "APPETITE ENHANCER", "APPETITE SUPPRESSANT", "APPLIANCE BULBS", "AQUARIUM ACCESSORIES", "AQUARIUMS/AQUARIUM KITS", "AQUATIC/REPTILE - GRAVEL/SOIL/SUBSTRATE", "AQUATIC/REPTILE - PLANT/WATER TREATMENTS", "AQUATIC/REPTILE - WATER TESTING KITS", "ASIAN BREAD ACCOMPANIMENTS - AMBIENT", "ASIAN BREAD ACCOMPANIMENTS - FRESH", "ASIAN BREAD ACCOMPANIMENTS - FROZEN", "ASTHMA REMEDIES", "ASTHMA REMEDIES - INHALER", "AUTO DISH ADDITIVES/BOOSTER", "AUTO DISH DETERGENT", "AUTO DISH DETERGENT COMBINATION", "AUTO DISH GLASS CARE", "AUTO DISH RINSE AID", "AUTO DISH SALT", "AUTO DISH WASHER FRESHENERS", "AUTOMOTIVE AIR FRESHENERS", "BABY CARE - COMBINATION/ GIFT PACKS", "BABY CHANGING/HYGIENE MATS", "BABY COLIC REMEDIES", "BABY CRADLE CAP REMEDIES", "BABY DIAPER RELATED PRODUCTS", "BABY DIAPERS - DISPOSABLE", "BABY DIAPERS - NON DISPOSABLE", "BABY DIAPERS - PULL UP/TRAINER PANTS", "BABY DIAPERS - SWIMMING", "BABY FOOD - SAVOURY DRY", "BABY FOOD - SAVOURY OTHER", "BABY FOOD - SAVOURY WET", "BABY FOOD - SWEET DRY", "BABY FOOD - SWEET OTHER", "BABY FOOD - SWEET WET", "BABY MILK FORMULA", "BABY NAPPY RASH REMEDIES", "BABY/NURSING - ACCESSORIES", "BAG CLIPS", "BAGELS - AMBIENT", "BAGELS - FRESH", "BAGELS - FROZEN", "BAGS REFUSE", "BAGUETTE/STICKS - AMBIENT", "BAGUETTE/STICKS - FRESH", "BAGUETTE/STICKS - FROZEN", "BAKING INGREDIENTS - AMBIENT", "BAKING/COOKING LINERS - REUSABLE", "BAKING/DESSERT MIX - AMBIENT", "BAKING/DESSERT MIX - FRESH", "BAKING/DESSERT MIX - FROZEN", "BANDAGE ADHESIVE", "BANDAGE NON STERILE", "BANDAGE SUPPORT", "BANDED PACKS - BEVERAGES", "BANDED PACKS - CONFECTIONERY & SNACKS & SWEET BISCUITS", "BANDED PACKS - DURABLE PRODUCTS", "BANDED PACKS - FOOD - AMBIENT", "BANDED PACKS - FOOD - FROZEN", "BANDED PACKS - FOOD - PERISHABLE", "BANDED PACKS - HEALTHCARE & PERSONAL CARE & BEAUTY PRODUCTS", "BANDED PACKS - HOMECARE", "BANDED PACKS - PET FOOD & CARE", "BANDED PACKS - UNIDENTIFIED", "BARLEY PRODUCTS - AMBIENT", "BARLEY PRODUCTS - FROZEN", "BARRIER CREAM/LIQUID/WIPES", "BARTENDING ACCESSORIES", "BATH ADDITIVES", "BATH SPAS", "BATTERIES NON-RECHARGEABLE", "BATTERIES RECHARGEABLE", "BEARD/NASAL HAIR TRIMMERS", "BEAUTY/COSMETIC AIDS", "BEER", "BEER/MALT - LOW/NON ALCOHOLIC", "BEVERAGE CARBONATING MACHINES & ACCESSORIES", "BIKINI TRIMMER - FEMALE", "BIRD DRINKS", "BIRD FOOD", "BISCUIT/CONFECTIONERY/SNACK ASSORTMENT", "BITTERS", "BLADDER & KIDNEY MEDICATION", "BLADDER MEDICATION", "BLEACH/AMMONIA", "BLISTER DRESSINGS LIQUID", "BLOOD PRESSURE MONITORS", "BODY & FACE BRONZER", "BODY & FACE ILLUMINATOR", "BODY & FACE SKIN POWDER", "BODY FAT MONITORS", "BODY/BODY & FACE FOUNDATION LIQUID", "BODY/BODY & FACE FOUNDATION POWDER", "BODY/FACIAL HAIR REGROWTH INHIBITOR - FEMALE", "BODY/FACIAL HAIR REGROWTH INHIBITOR - MALE", "BODY/FACIAL/FOOT CLEANSERS/EXFOLIATORS - ELECTRIC", "BONE DISEASES MEDICATION", "BOWLS - DISPOSABLE", "BRANDY - GRAPE", "BREAD - OTHER - FRESH", "BREAD - OTHER - FROZEN", "BREADS - OTHER - AMBIENT", "BREADS PIZZA STYLE - FRESH", "BREADS PIZZA STYLE - FROZEN", "BREADS SPECIALITIES - AMBIENT", "BREADS SPECIALITIES - FROZEN", "BREADS SPECIALITIES - LOAVES - FRESH", "BREADSTICKS/CRISPBREAD/CEREAL BASED CAKES - AMBIENT", "BREAKFAST CEREALS - FRESH", "BREAST PADS/SHELLS/ NIPPLE SHIELDS", "BREAST SELF EXAMINATION KITS", "BREATH FRESHENERS", "BREATHING AIDS - NASAL STRIPS", "BRIOCHE - AMBIENT", "BRIOCHE - FRESH", "BRIOCHE - FROZEN", "BUCKETS HOUSEHOLD", "BUCKWHEAT PRODUCTS - AMBIENT", "BUCKWHEAT PRODUCTS - FROZEN", "BURN RELIEF CREAM/GEL/LIQUID", "BUTTER/MARG/EDIBLE FATS - AMBIENT", "BUTTER/MARG/EDIBLE FATS - FRESH", "BUTTER/MARG/EDIBLE FATS - FROZEN", "CAKE BOARDS- DISPOSABLE", "CAKES/GATEAUX - AMBIENT", "CAKES/GATEAUX - FRESH", "CAKES/GATEAUX - FROZEN", "CALMING PRODUCTS", "CANDLES", "CANDLES & INCENSE - COMBINATION PACKS", "CARBOHYDRATE MIX - AMBIENT", "CARBOHYDRATE MIX - FRESH", "CARBOHYDRATE MIX - FROZEN", "CARBONATED SOFT DRINKS - COLA", "CARBONATED SOFT DRINKS - NON COLA", "CARPET CLEANING SYSTEM", "CARPET FRESHENERS", "CAT FOOD - DRY", "CAT FOOD - MILK/DRINKS", "CAT FOOD - OTHER", "CAT FOOD - TREATS", "CAT FOOD - WET", "CATHETERS & ACCESSORIES", "CEREAL/FRUIT/MUESLI BARS", "CEREAL/GRAIN - AMBIENT", "CEREALS/TOASTER PASTRIES - AMBIENT", "CEREALS/TOASTER PASTRIES - FROZEN", "CHEESE - OTHER - FRESH", "CHEESE ASSORTMENTS - FRESH", "CHEESE BLOCKS - FRESH", "CHEESE GRATED - FRESH", "CHEESE NATURAL - AMBIENT", "CHEESE NATURAL - FRESH", "CHEESE NATURAL - FROZEN", "CHEESE PICK & MIX - FRESH", "CHEESE PROCESSED - AMBIENT", "CHEESE PROCESSED - FRESH", "CHEESE PROCESSED - FROZEN", "CHOCOLATE - ASSORTED", "CHOCOLATE - BAR", "CHOCOLATE - MINIS", "CHOCOLATE - OTHER", "CHOCOLATE NOVELTIES - EGGS", "CHOCOLATE NOVELTIES - MOULDED", "CHOCOLATE/MILK FLAVOURING - DRINKS POWDER", "CIABATTA - AMBIENT", "CIABATTA - FRESH", "CIABATTA - FROZEN", "CIDER/PERRY - APPLE/PEAR BASED", "CIGARETTES", "CIGARS", "CIRCULATORY PRODUCTS", "CIRCULATORY PRODUCTS CAPSULES/TABLETS", "CLEANING BRUSHES", "CLEANING CLOTHS/SYSTEM", "CLEANING/DUSTING SYSTEM - COMPLETE KITS", "CLEANSERS/ TOILET SOAP", "CLEANSING - BODY WASH - CREAM/GEL/LIQUID", "COCOA/CHOCOLATE DRINKS", "COFFEE - OTHER", "COFFEE - READY TO DRINK", "COFFEE - ROAST GROUND", "COFFEE - SOLUBLE INSTANT", "COFFEE - WHOLE BEANS", "COFFEE ENHANCERS/FLAVOURINGS - AMBIENT", "COFFEE SUBSTITUTES - OTHER", "COFFEE SUBSTITUTES - ROAST GROUND", "COFFEE SUBSTITUTES - SOLUBLE INSTANT", "COLD SORE TREATMENT", "COLD/FLU REMEDIES", "COMBINED CAT & DOG FOOD", "COMBINED FRUIT & VEGETABLES - AMBIENT", "CONCENTRATES/CORDIAL/SQUASHES/SYRUPS", "CONTACT LENS CARE LIQUID/LOTION", "CONTACT LENS CARE PADS", "CONTACT LENS CARE TABLETS", "CONTRACEPTIVE CAP/DIAPHRAGM/IUD/SPONGE", "CONTRACEPTIVE CONDOMS", "CONTRACEPTIVE FEMIDOMS", "CONTRACEPTIVE IMPLANT/PATCH", "CONTRACEPTIVE MORNING AFTER PILL", "CONTRACEPTIVE PILL", "CONTRACEPTIVE SPERMICIDE", "COOKING UTENSILS", "COOKWARE DISPOSABLE", "COOLING STRIPS", "CORTICOSTEROIDS", "COSMETIC REMOVER - LIQUID", "COSMETIC REMOVER - WIPES", "COTTON WOOL - BALLS", "COTTON WOOL - BUDS", "COTTON WOOL - OTHER", "COTTON WOOL - PADS", "COUGH REMEDIES", "COUSCOUS PRODUCTS - AMBIENT", "COUSCOUS PRODUCTS - FRESH", "COUSCOUS PRODUCTS - FROZEN", "CREAM - AMBIENT", "CREAM - FRESH", "CREAM - FROZEN", "CREAM CULTURED - AMBIENT", "CREAM CULTURED - FRESH", "CREAM CULTURED - FROZEN", "CREAM SUBSTITUTES - AMBIENT", "CREAM SUBSTITUTES - FRESH", "CREAM SUBSTITUTES - FROZEN", "CREAMERS - AMBIENT", "CREAMERS - FRESH", "CREAMERS - FROZEN", "CROISSANT - AMBIENT", "CROISSANT - FRESH", "CROISSANT - FROZEN", "CROUTONS - AMBIENT", "CRUMPETS/ENGLISH MUFFINS - AMBIENT", "CRUMPETS/ENGLISH MUFFINS - FRESH", "CRUMPETS/ENGLISH MUFFINS - FROZEN", "CUTLERY - DISPOSABLE", "CUTLERY - NON DISPOSABLE", "DAILY LIVING AIDS", "DAIRY - AMBIENT - OTHER", "DECOLOURANTS - HAIR", "DECORATION PIPING BAGS", "DECORATIVE LIGHTS", "DENTAL ACCESSORIES", "DENTAL FLOSS/TAPE", "DENTURE CARE", "DEODORANTS", "DEPILATORIES - FEMALE - CREAM/FOAM/GEL", "DEPILATORIES - FEMALE - OTHER", "DEPILATORIES - FEMALE - STRIPS", "DEPILATORIES - FEMALE - WAX", "DEPILATORIES - MALE - CREAM/FOAM/GEL", "DEPILATORIES - MALE - OTHER", "DEPILATORIES - MALE - STRIPS", "DEPILATORIES - MALE - WAX", "DESSERT SAUCES - AMBIENT", "DESSERT SAUCES - FRESH", "DESSERT SAUCES - FROZEN", "DESSERTS - AMBIENT", "DESSERTS - FRESH", "DESSERTS - FROZEN", "DEXTERITY AIDS", "DIAGNOSTIC TESTS - BLOOD BASED", "DIAGNOSTIC TESTS - HAIR BASED", "DIAGNOSTIC TESTS - NOSE/THROAT SWABS", "DIAGNOSTIC TESTS - SALIVA BASED", "DIAGNOSTIC TESTS - URINE BASED", "DIARRHOEA REMEDIES", "DIGESTIVE ENZYME SUPPLEMENT", "DIPS/DRESSINGS/SAUCES - AMBIENT", "DIPS/DRESSINGS/SAUCES - FRESH", "DIPS/DRESSINGS/SAUCES - FROZEN", "DISH PRE WASH TREATMENT/BOOSTER LIQUID", "DIURETICS", "DOG FOOD - DRY", "DOG FOOD - MILK/DRINKS", "DOG FOOD - OTHER", "DOG FOOD - TREATS", "DOG FOOD - WET", "DOUGH PRODUCTS - AMBIENT", "DOUGH PRODUCTS - FRESH", "DOUGH PRODUCTS - FROZEN", "DRAIN PIPE PLUNGERS", "DRINKING STRAWS - DISPOSABLE", "DRINKING STRAWS - NON DISPOSABLE", "DRINKWARE - DISPOSABLE", "DRINKWARE - NON DISPOSABLE", "DRINKWARE LIDS - NON DISPOSABLE", "DRY CLEANING", "DUST BRUSHES", "DUST PANS & BRUSHES", "EAR CARE ANTI ITCH REMEDY", "EAR CARE CLEANING", "EAR CARE PAIN RELIEF", "EAR CARE WAX TREATMENT DROPS", "EAR PLUGS", "EGGS - AMBIENT", "EGGS - FRESH", "EGGS/EGG PRODUCTS - FROZEN", "ELECTRONIC CIGARETTES", "EMOLLIENTS & WOUND HEALING CREAM/GEL/OIL", "EMOLLIENTS & WOUND HEALING PLASTER", "EMOLLIENTS & WOUND HEALING POWDER - MULTI DOSE", "EMOLLIENTS & WOUND HEALING POWDER - SINGLE DOSE", "ENDOCRINE THERAPY", "ENERGY DRINKS - STIMULANTS", "ENERGY INHALANT - SOLID/STICK", "ENERGY PRODUCTS - CAPSULES/GUM/STRIPS/TABLETS", "ENERGY/SPORTS BARS", "EPILATORS/IPL/LASER HAIR REMOVERS - ELECTRIC", "EYE ALLERGY/INFECTION TREATMENT - GEL/LIQUID", "EYE BROW COSMETICS", "EYE COSMETIC KITS", "EYE LINERS", "EYE MASCARA", "EYE PREPARATIONS", "EYE SHADOW", "FABRIC SOFTENERS", "FACE BLUSHER", "FACE BRONZER", "FACE CONCEALER/CORRECTOR", "FACE COSMETIC KITS", "FACE FOUNDATION/MAKE UP BASE", "FACE POWDER", "FACE SOAP - BARS", "FACE WASH", "FACIAL SAUNAS", "FACIAL WIPES/TISSUES", "FALSE EYELASHES", "FALSE NAILS", "FERMENTED MILK/ MILK SUBSTITUTE", "FERTILITY AIDS", "FILLINGS/PASTES/SPREADS - SAVOURY - AMBIENT", "FILLINGS/PASTES/SPREADS - SAVOURY - FRESH", "FILLINGS/PASTES/SPREADS - SAVOURY - FROZEN", "FILLINGS/PASTES/SPREADS - SWEET - AMBIENT", "FILLINGS/PASTES/SPREADS - SWEET - FRESH", "FILLINGS/PASTES/SPREADS - SWEET - FROZEN", "FILTERS HOT BEVERAGE - DISPOSABLE", "FILTERS HOT BEVERAGE - NON DISPOSABLE", "FILTERS HOT BEVERAGE - SUPPORT", "FIRST AID - PINS AND FASTENERS", "FIRST AID KITS", "FIRST AID SCISSORS", "FISH FOOD/SNACKS", "FISH PARASITE/FIN ROT CRYSTAL/POWDER", "FISH PARASITE/FIN ROT LIQUID", "FISH PARASITE/FIN ROT TABLETS", "FISH/SHELLFISH/SEAFOOD - AMBIENT", "FISH/SHELLFISH/SEAFOOD - FRESH", "FISH/SHELLFISH/SEAFOOD - FROZEN", "FLAVOURED APERITIFS/MIXERS - BITTER FRUITS/GINGER ALE", "FLAVOURED MILK", "FLOOR BROOMS/MOPS", "FLOUR - AMBIENT", "FLUORESCENT TUBES", "FLY SWATTER", "FOCACCIA - AMBIENT", "FOCACCIA - FRESH", "FOCACCIA - FROZEN", "FOOD - OTHER - FRESH", "FOOD - OTHER - FROZEN", "FOOD CLEANERS", "FOOD PRESERVATION DEVICES", "FOOD STORAGE CONTAINERS", "FOOT - BLISTER PREVENTION", "FOOT - CALLUS/CORN TREATMENTS", "FOOT - CHILBLAIN - BALM/CREAM", "FOOT - INGROWN TOENAIL - CREAM/GEL/LIQUID", "FOOT - INSOLES", "FOOT - ORTHOPAEDIC FOOTWEAR", "FOOT - TOE SEPARATOR PADS", "FOOT - VERRUCA SOCKS", "FOOT BATH/MASSAGER", "FOOT CARE KIT", "FOOT/HEEL/TOE CAPS/CUSHIONS/PADS", "FRAGRANCE/PERFUME", "FRAGRANCES/GROOMING/COSMETIC COMBINATION PACKS", "FREEZER SUPPLIES", "FRUIT - FRESH", "FRUIT - FROZEN", "FRUIT & NUT COMBINATION - FRESH", "FRUIT & NUT COMBINATION - FROZEN", "FRUIT & VEGETABLE COMBINATIONS - FRESH", "FRUIT & VEGETABLE COMBINATIONS - FROZEN", "FRUIT DRESSED - AMBIENT", "FRUIT DRIED - AMBIENT", "FRUIT PROCESSED - AMBIENT", "FRUIT SPECIALITY - AMBIENT", "FRUIT/NUT/SEED COMBINATIONS - AMBIENT", "FRUIT/VEGETABLE LINERS", "FURNITURE POLISH", "FUSES", "GALL BLADDER & LIVER MEDICATION", "GAUZE SWABS NON STERILE", "GAUZE SWABS STERILE", "GENERAL PERSONAL HYGIENE - OTHER", "GENEVER", "GENITAL MEDICATION/ TREATMENT", "GIN/GIN STYLE", "GLOVES", "GLOVES MEDICAL - DISPOSABLE", "GROOMING/BATHING AIDS", "GROWTH HORMONES", "GYNAECOLOGICAL INFECTION TEST KITS", "HAIR BRUSHES/COMBS & DECORATIVE/STYLING ACCESSORIES", "HAIR CLEANING SHAMPOO - BARS", "HAIR CLEANING SHAMPOO - CREAM/GEL/LIQUID", "HAIR CLEANING SHAMPOO - OTHERS", "HAIR CLEANING SHAMPOO - POWDER", "HAIR COLOURANTS", "HAIR COLOURING ACCESSORIES", "HAIR CONDITIONERS", "HAIR CONDITIONING CAPS/HOODS", "HAIR DRYERS", "HAIR STYLERS", "HAIR STYLING", "HAIR STYLING AIDS", "HAIR TREATMENTS", "HAIR WIGS AND ACCESSORIES", "HAND DISH DETERGENT", "HAND PAPER/TOWELS", "HAND SANITIZERS", "HANDLE DUSTERS", "HANGOVER CURES/PREVENTIONS - CAPSULES/TABLETS", "HEAD LICE COMBS", "HEAD LICE TREATMENTS", "HEALTH SUPPLEMENTS - COMBINATIONS", "HEARING AID ACCESSORIES", "HEART RATE MONITORS", "HEAT NOT BURN", "HEATED PACKS", "HERBAL/BOTANICAL REMEDIES/TREATMENTS", "HERBAL/BOTANICAL SUPPLEMENTS", "HERBS/SPICES - AMBIENT", "HERBS/SPICES - FRESH", "HERBS/SPICES - FROZEN", "HOME BARBERS", "HOME BREWING AND WINE MAKING", "HOME CANNING/BOTTLING", "HOMEOPATHIC REMEDIES/TREATMENTS", "HONEY - AMBIENT", "HOOD FILTERS", "HOT COOKING SAUCE - AMBIENT", "HOUSEHOLD ANTI ALLERGEN TREATMENT", "HOUSEHOLD BINS", "HOUSEHOLD CLEANERS", "HOUSEHOLD CLEANING ACCESSORIES COMBINATION PACKS", "HOUSEHOLD CLEANING HARDWARE - OTHER", "HOUSEHOLD DISINFECTANTS", "HOUSEHOLD LIMESCALE/MILDEW/MOULD", "HOUSEHOLD SCISSORS", "HOUSEHOLD STAIN REMOVERS", "HOUSEHOLD WATER SOFTENERS", "HOUSEHOLD WIPES/DISINFECTANT WIPES", "HUMIDIFIERS/DEHUMIDIFIERS", "HYGIENE COVERS", "ICE - EDIBLE - FROZEN", "ICE BAGS - MEDICAL", "ICE CREAM/NOVELTIES/SORBET/YOGURT - FROZEN", "ICE CUBE BAGS", "ICE PACKS/PADS", "ICE/HEATED PACKS COMBINED", "IMMUNE SYSTEM ENHANCERS", "IMMUNOSTIMULANTS - LIQUID INTERNAL USE - SINGLE DOSE", "IMMUNOSUPPRESSANTS - CAPSULES/TABLETS", "INCENSE", "INCONTINENCE LINERS/PADS", "INCONTINENCE PANTS", "INCONTINENCE PROTECTION SHEETS", "INFIDELITY TEST KITS", "INFLAMMATORY BOWEL DISEASE MEDICATION", "INFUSIONS - FRUIT/HERBAL - BAGS/SINGLE PORTION", "INFUSIONS - FRUIT/HERBAL - INSTANT", "INFUSIONS - FRUIT/HERBAL - OTHER", "INFUSIONS - FRUIT/HERBAL - READY TO DRINK", "INJURY SUPPORTS", "INSECT BITE TREATMENTS", "INSECT CATCHERS", "INSECT CONTROL - ATTRACTANT/BAIT DEVICE", "INSECT CONTROL - BALL/TABLET", "INSECT CONTROL - BURNER", "INSECT CONTROL - CANDLES", "INSECT CONTROL - COIL/INCENSE", "INSECT CONTROL - ELECTRIC", "INSECT CONTROL - FUMIGATION PRODUCTS", "INSECT CONTROL - NON ELECTRIC - LIQUID/GEL/POWDER", "INSECT FOOD/SNACKS", "INSECT REPELLENT (PERSONAL)", "INSECT/BIRD/POLLEN REPELLENTS - SCREEN/NETS", "INSULATED BOTTLES/CUPS/FLASKS/MUGS", "INSULIN", "INSULIN PEN NEEDLES - DISPOSABLE", "INSULIN PENS", "INTESTINAL FLORA REMEDIES", "INTIMATE LUBRICATION CREAM/GEL/LIQUID", "INTIMATE LUBRICATION SUPPOSITORIES", "INTRAVENOUS SOLUTIONS", "JAMS/MARMALADE - AMBIENT", "JAMS/MARMALADE - FRESH", "JAMS/MARMALADE - FROZEN", "JOINT PRODUCTS", "JUICE", "JUICE BASED DRINKS", "KETCHUP - AMBIENT", "KIDNEY MEDICATION", "KITCHEN ACCESSORIES", "KITCHEN PAPER/TOWEL - DISPOSABLE", "KITCHEN SCALES", "KITCHENWARE - COMBINATION PACKS - DISPOSABLE", "LANCETS", "LARGE MAMMAL FOOD/SNACKS", "LAUNDRY - FABRIC PROTECTANTS", "LAUNDRY - OTHER", "LAUNDRY BOOSTERS AND STAIN REMOVERS - LIQUID", "LAUNDRY BOOSTERS AND STAIN REMOVERS - OTHER", "LAUNDRY BOOSTERS AND STAIN REMOVERS - POWDER", "LAUNDRY BOOSTERS AND STAIN REMOVERS - TABLET", "LAUNDRY COLOUR CARE", "LAUNDRY DETERGENTS - BALLS - MACHINE WASH", "LAUNDRY DETERGENTS - CAPSULE/TABLET - MACHINE WASH", "LAUNDRY DETERGENTS - FLAKES/GRANULES/POWDER - HAND WASH", "LAUNDRY DETERGENTS - FLAKES/GRANULES/POWDER - MACHINE WASH", "LAUNDRY DETERGENTS - KITS", "LAUNDRY DETERGENTS - LIQUID AND GEL - HAND WASH", "LAUNDRY DETERGENTS - LIQUID AND GEL - MACHINE WASH", "LAUNDRY DETERGENTS - SHEETS", "LAUNDRY DETERGENTS - SOAP NUTS", "LAUNDRY DETERGENTS - SOLID BARS/BLOCKS", "LAUNDRY DISINFECTANT", "LAUNDRY DYES", "LAUNDRY STARCH", "LAUNDRY WATER SOFTENERS", "LAUNDRY WHITENERS", "LAXATIVES", "LIGHT BULBS", "LIGHTER FLINTS/WICKS", "LIGHTER FLUID/GAS", "LIGHTERS", "LIP COSMETIC KITS", "LIP GLOSS", "LIP LINER", "LIP STICK", "LIP VOLUMISER", "LIQUEURS", "LIVER MEDICATION", "MADEIRA", "MAGNETIC THERAPY", "MALE FERTILITY TEST KITS", "MALTED DRINKS", "MANICURING/PEDICURING AIDS - ELECTRIC", "MANICURING/PEDICURING TOOL", "MARINADES - AMBIENT", "MARINADES - DRY - AMBIENT", "MARINADES - WET - FRESH", "MARSALA", "MASKS - DUST/FIRST AID/SURGICAL", "MASSAGE PRODUCTS", "MAYONNAISE - AMBIENT", "MAYONNAISE - FRESH", "MEAL KITS - AMBIENT", "MEAL KITS - FRESH", "MEAL KITS - FROZEN", "MEASURING/MIXING CUPS/BOWLS", "MEAT ALTERNATIVES - AMBIENT", "MEAT ALTERNATIVES - FRESH", "MEAT ALTERNATIVES - FROZEN", "MEAT PRODUCTS - AMBIENT", "MEAT PRODUCTS - FRESH", "MEAT PRODUCTS - FROZEN", "MEAT/FISH/SEAFOOD COMBINATIONS - AMBIENT", "MEAT/FISH/SEAFOOD COMBINATIONS - FRESH", "MEAT/FISH/SEAFOOD COMBINATIONS - FROZEN", "MEDICAL IDENTIFICATION PRODUCTS", "MEDICAL/SURGICAL INSTRUMENTS/SUPPLIES", "MEDICATED SKIN TREATMENT", "MEDICATION APPLICATORS/CONTAINERS/SORTERS", "MEDICINAL TREATMENTS - COMBINATION PACK", "MEMORY PRODUCTS", "MENOPAUSE PRODUCTS", "METAL POLISH", "MEXICAN ACCOMPANIMENT BAKERY - FRESH", "MEXICAN BREAD ACCOMPANIMENTS - AMBIENT", "MEXICAN BREAD ACCOMPANIMENTS - FROZEN", "MEZCAL", "MIDDLE EAR MONITORS", "MILK ANIMAL - AMBIENT", "MILK ANIMAL - FRESH", "MILK ANIMAL - FROZEN", "MILK EVAPORATED/CONDENSED - AMBIENT", "MILK SUBSTITUTES - FLAVOURED", "MILK SUBSTITUTES - NON FLAVOURED - AMBIENT", "MILK SUBSTITUTES - NON FLAVOURED - FRESH", "MILK SUBSTITUTES - NON FLAVOURED - FROZEN", "MILLET PRODUCTS - AMBIENT", "MINERAL SUPPLEMENTS", "MINERAL WATERS FLAVOURED", "MINERAL WATERS NON FLAVOURED", "MINT SAUCE - AMBIENT", "MINT SAUCE - FRESH", "MOBILITY AIDS & ACCESSORIES", "MONTILLA", "MOUTHWASH/ORAL RINSES/ORAL RINSE ANTISEPTICS", "MULTI PURPOSE SKIN/FACE/EYE DECORATION", "MUSCLE-SKELETAL DISEASES MEDICATION/ENZYMES", "MUSCULAR PAIN RELIEF - ORAL", "MUSCULAR PAIN RELIEF - TOPICAL", "MUSTARD - AMBIENT", "MUSTARD - FRESH", "NAIL CARE - KITS", "NAIL DECORATION", "NAIL POLISH", "NAIL POLISH REMOVER", "NAIL WHITENER", "NAIL/CUTICLE TREATMENTS", "NAPKINS/SERVIETTES - DISPOSABLE", "NASAL DECONGESTANT - CHEST RUB", "NASAL DECONGESTANT - NOSE BALM", "NASAL DECONGESTANT INHALANT", "NASAL DECONGESTANT ORAL REMEDIES", "NASAL TREATMENT", "NERVOUS SYSTEM PRODUCTS", "NON CARBONATED SOFT DRINKS", "NON-DISPOSABLE GROCERY BAGS", "NOODLES - FRESH", "NOODLES - FROZEN", "NOODLES - ORIENTAL STYLE - AMBIENT", "NUT BUTTER - AMBIENT", "NUT BUTTER - FRESH", "NUTS - AMBIENT", "NUTS - FRESH", "NUTS - FROZEN", "OILS EDIBLE - BLENDS - AMBIENT", "OILS EDIBLE - CORN/MAIZE - AMBIENT", "OILS EDIBLE - FRUIT/PULP BASED - AMBIENT", "OILS EDIBLE - GRAIN BASED - AMBIENT", "OILS EDIBLE - NUT BASED (EXC PEANUT/GROUNDNUT) - AMBIENT", "OILS EDIBLE - OLIVE - AMBIENT", "OILS EDIBLE - OTHER - AMBIENT", "OILS EDIBLE - PALM/PALM KERNEL - AMBIENT", "OILS EDIBLE - PEANUT/GROUNDNUT - AMBIENT", "OILS EDIBLE - SEED BASED (EXC SUNFLOWER) - AMBIENT", "OILS EDIBLE - SOYABEAN - AMBIENT", "OILS EDIBLE - SUNFLOWER - AMBIENT", "ORAL ANALGESICS", "ORAL BEAUTY TREATMENTS", "ORAL GUARDS", "ORAL HYGIENE - COMBINATION PACKS", "ORAL REPAIR - CAVITY FILLERS", "ORAL REPAIR - KITS", "ORAL SWABS", "ORAL TREATMENT", "ORTHODONTIC CARE", "ORTHOPEDIC AIDS", "OSTOMY PRODUCTS", "OTHER GYNECOLOGICALS", "OTHER INCONTINENCE PRODUCTS", "OVEN PROTECTORS - DISPOSABLE", "OVULATION PRODUCTS", "PAIN RELIEF/MUSCLE STIMULATOR APPLIANCES & ACCESSORIES", "PANCAKES SAVOURY NON FILLED - FRESH", "PAPER BAKING/COOKING CUPS - DISPOSABLE", "PAPER COASTERS/DOILIES - DISPOSABLE", "PAPER/PLASTIC BAGS - STORAGE/COOKING", "PAPER/PLASTIC ROLLS - STORAGE/COOKING", "PAPER/PLASTIC SHEETS - STORAGE/COOKING", "PASTA - AMBIENT", "PASTA - FRESH", "PASTA - FROZEN", "PEAK FLOW MONITORS", "PEPPER - AMBIENT", "PERSONAL CARE WIPES", "PERSONAL GROOMING COMBINATION & TRAVEL PACKS", "PERSONAL MASSAGERS - ELECTRIC", "PERSONAL MASSAGERS - REPLACEMENT PARTS", "PEST CONTROL", "PEST CONTROL - ATTRACTANT/BAIT DEVICE", "PET ATTRACTANTS", "PET BED/CAGE/TRAY - CLEANING/DISINFECTANT", "PET CAGE/BASKET/BEDDING/COMFORT", "PET CLOTHING/WALKING ACCESSORIES", "PET COAT CARE- CLEANING/DISINFECTING", "PET DEODORANTS", "PET DETERRENTS", "PET DIETARY SUPPLEMENTS/TREATMENTS", "PET DOOR/FLAPS", "PET EDUCATION/TOYS", "PET FEEDING ACCESSORIES", "PET FLEA/TICK TREATMENT", "PET GROOMING HARDWARE", "PET HEALTH - OTHER", "PET HYGIENE", "PET LITTER", "PET LITTER ACCESSORIES", "PET WORMING TREATMENT", "PICKLES/PICALLILI - AMBIENT", "PIPE OPENERS/TREATMENTS", "PITTA BREAD - AMBIENT", "PITTA BREAD - FRESH", "PITTA BREAD - FROZEN", "PIZZA - FRESH", "PIZZA - FROZEN", "PIZZA BASES/KITS - AMBIENT", "PIZZA BASES/KITS - FRESH", "PIZZA BASES/KITS - FROZEN", "PLACE MATS - DISPOSABLE", "PLANT POISON/TOXIN REMOVAL", "PLASTER ADHESIVE REMOVER", "PLASTERS", "PLATES - DISPOSABLE", "PLUGS", "PLUGS NASAL", "POLENTA - AMBIENT", "POLENTA - FRESH", "POLENTA - FROZEN", "PORT", "PORT STYLE (NON PORTUGUESE)", "POST DEPILATORY CARE - FEMALE", "POTATO - AMBIENT", "POTATO - FRESH", "POTATO - FROZEN", "POTATO GNOCCHI/MEALS - AMBIENT", "POTATO GNOCCHI/MEALS - FRESH", "POTATO GNOCCHI/MEALS - FROZEN", "PRE DEPILATORY PRODUCTS - FEMALE", "PRE DEPILATORY PRODUCTS - MALE", "PREPARED BASES - AMBIENT", "PREPARED BASES - FRESH", "PREPARED BASES - FROZEN", "PREPARED COATINGS/ICINGS/FROSTINGS - AMBIENT", "PREPARED COATINGS/ICINGS/FROSTINGS - FRESH", "PRESERVING WAX BLOCK", "PROSTATE MEDICATION", "PSORIASIS/ECZEMA REMEDIES", "PULSE MONITORS", "PURE AROMATHERAPY/ESSENTIAL OILS", "QUINOA PRODUCTS - AMBIENT", "QUINOA PRODUCTS - FRESH", "QUINOA PRODUCTS - FROZEN", "RAISING AGENTS - AMBIENT", "RAISING AGENTS - FRESH", "RAZOR BLADES - FEMALE", "RAZOR BLADES - MALE/UNISEX", "RAZORS DISPOSABLE - FEMALE", "RAZORS DISPOSABLE - MALE/UNISEX", "RAZORS NON DISPOSABLE - FEMALE", "RAZORS NON DISPOSABLE - MALE/UNISEX", "READY MEALS - FRESH", "RECIPE MIXES - AMBIENT", "RECIPE MIXES - BREAD BASED - AMBIENT", "RECIPE MIXES - BREAD BASED - FRESH", "RECIPE MIXES - BREAD BASED - FROZEN", "REHYDRATION SUPPLEMENT", "RELAXATION DURABLES", "REPTILE FOOD/SNACKS", "RESPIRATORY INHALERS", "RICE/RICE BASED MEALS - AMBIENT", "RICE/RICE BASED MEALS - FRESH", "RICE/RICE BASED MEALS - FROZEN", "ROLLS - AMBIENT", "ROLLS - FRESH", "ROLLS - FROZEN", "RUM/RUM STYLE", "SALAD READY TO EAT - FRESH", "SALAD SHAKING BAGS", "SALADS - AMBIENT", "SALT- AMBIENT", "SANDWICHES/FILLED ROLLS/WRAPS - AMBIENT", "SANDWICHES/FILLED ROLLS/WRAPS - FRESH", "SANDWICHES/FILLED ROLLS/WRAPS - FROZEN", "SANITARY PROTECTION - CUPS", "SANITARY PROTECTION - DISPOSABLE BAGS", "SANITARY PROTECTION - MATERNITY PADS/TOWELS/PANTS", "SANITARY PROTECTION - PADS/TOWELS", "SANITARY PROTECTION - PANTS", "SANITARY PROTECTION - PANTYLINERS", "SANITARY PROTECTION - TAMPONS", "SAVOURY CRACKERS/BISCUITS", "SAVOURY CRACKERS/BISCUITS - DOUGH", "SAVOURY PASTRY - FRESH", "SAVOURY PASTRY - FROZEN", "SCABIES CREAM/LIQUID", "SCAR REDUCTION - SILICON DRESSING", "SEAFOOD/COCKTAIL SAUCE - AMBIENT", "SEEDS - AMBIENT", "SELF TANNING", "SEPTIC TANK TREATMENTS", "SEX HORMONES", "SEXUAL DRIVE MEDICATION", "SHAVER REPLACEMENT PARTS", "SHAVERS FEMALE", "SHAVERS MALE", "SHAVING AIDS - SHAVING BRUSHES", "SHAVING BAR/CREAM/OIL/FOAM - MALE/UNISEX", "SHAVING CREAM/LOTION - FEMALE", "SHAVING/DEPILATION - FEMALE - OTHER", "SHAVING/DEPILATION - MALE - OTHER", "SHELLS - SEAFOOD/SNAILS", "SHERRY - JEREZ", "SHERRY STYLE (NON JEREZ)", "SHOE ACCESSORIES", "SHOE APPLICATIONS CLEANERS", "SHOE APPLICATIONS DEODORISER/DISINFECTANT", "SHOE APPLICATIONS POLISH", "SHOE APPLICATIONS WATERPROOFING/DUBBIN", "SHOE APPLICATIONS WHITENERS", "SHOE POLISH KITS", "SKEWERS - DISPOSABLE", "SKIN CARE - CAPSULES/ PODS", "SKIN CARE - KITS/ TRAVEL SETS", "SKIN CARE TINTED", "SKIN FIRMING/ ANTI AGING", "SKIN HYDRATION MONITOR", "SKIN MASKS", "SKIN MOISTURIZER/LOTION/SERUM", "SKIN POWDER", "SKIN TONERS/ASTRINGENTS", "SLEEPING PRODUCTS", "SLICING/TIN STYLE LOAF - AMBIENT", "SLICING/TIN STYLE LOAF - FRESH", "SLICING/TIN STYLE LOAF - FROZEN", "SLIMMING AID - MEAL REPLACEMENT", "SLIMMING AID NON MEAL REPLACEMENT", "SMALL MAMMAL DRINKS", "SMALL MAMMAL FOOD/GIFT SELECTION PACK", "SMALL MAMMAL FOOD/SNACKS", "SMOKING ACCESSORIES - ASHTRAYS", "SMOKING ACCESSORIES - OTHERS", "SMOKING ACCESSORIES - PAPERS", "SNACKS - ASSORTED", "SNACKS - CHEESE PRODUCTS", "SNACKS - CHIPS/CRISPS - ASSORTMENT", "SNACKS - CHIPS/CRISPS - EXTRUDED", "SNACKS - CHIPS/CRISPS - SLICED", "SNACKS - CHIPS/CRISPS - TORTILLA", "SNACKS - COCONUT", "SNACKS - FISH/SEAFOOD PRODUCTS", "SNACKS - MEAT PRODUCTS", "SNACKS - POPCORN", "SNACKS - PRETZELS", "SNACKS - VEGETABLE PRODUCTS", "SNACKS DIPPING - SAVOURY - FRESH", "SNACKS DIPPING - SWEET - FRESH", "SOCKETS", "SOFT DRINKS - POWDER/ TABLETS", "SORE THROAT REMEDIES", "SOUP/BOUILLON/STOCK - AMBIENT", "SOUP/BOUILLON/STOCK - FRESH", "SOUP/BOUILLON/STOCK - FROZEN", "SPECIALIST CLEANSING - INTIMATE WASH", "SPECIALIST COMBINATION PACKS - AMBIENT", "SPIRITS - MINOR/REGIONAL STYLES", "SPIRITS - OTHERS", "SPORTS DRINKS - REHYDRATION/ISOTONIC", "STETHOSCOPES", "STORAGE CONTAINERS - HOUSEHOLD", "STRING", "STYPTIC PRODUCTS", "STYPTIC PRODUCTS - POWDER", "SUGAR/CANDY - ASSORTED", "SUGAR/CANDY - GUM", "SUGAR/CANDY - HARD", "SUGAR/CANDY - SOFT", "SUGAR/CANDY - SPECIALITIES", "SUGAR/SUGAR SUBSTITUTES/SYRUP/TREACLE - AMBIENT", "SUGAR/SUGAR SUBSTITUTES/SYRUP/TREACLE - FRESH", "SUGAR/SUGAR SUBSTITUTES/SYRUP/TREACLE - FROZEN", "SUNCARE - OTHER", "SUNSCREEN", "SURFACE FRESHENERS", "SURGICAL LUBRICANT - CREAM/GEL/LIQUID", "SURVIVAL BLANKETS", "SWEET BISCUITS", "SWEET BISCUITS DOUGH", "SWEET PASTRY/DOUGH - FROZEN", "SWEET PASTRY/DOUGHNUTS/PIES - AMBIENT", "SWEET PASTRY/DOUGHNUTS/PIES - FRESH", "SYRINGES DISPOSABLE", "TABLE ACCESSORIES - NON DISPOSABLE", "TABLE COVERINGS - DISPOSABLE", "TABLE SETTING POUCHES - DISPOSABLE", "TABLEMATS/POT MATS/COASTERS - NON DISPOSABLE", "TABLET SPLITTERS", "TABLEWARE - DINNER/PARTY SETS - DISPOSABLE", "TABLEWARE - NON DISPOSABLE", "TAN ACCELERATOR", "TEA - BAGS/SINGLE PORTION", "TEA - CONCENTRATE - LIQUID/FROZEN", "TEA - INSTANT - POWDER", "TEA - LOOSE/MULTI PORTION", "TEA - READY TO DRINK", "TEA & INFUSIONS - ASSORTMENT", "TEQUILA/TEQUILA STYLE", "TEXTILE FRESHENERS", "THERAPEUTIC HOSIERY", "THERMOMETERS PERSONAL - PROBE COVERS DISPOSABLE", "THERMOMETERS PERSONAL DIGITAL", "THERMOMETERS PERSONAL MERCURY", "THERMOMETERS PERSONAL STRIPS", "THICKENING AGENT - AMBIENT", "TOBACCO - LOOSE", "TOBACCO CHEW/SNUS", "TOBACCO FOR PIPES/SHISHA", "TOBACCO SNUFF", "TOBACCO WHOLE LEAF", "TOILET CLEANERS/FRESHENERS CONTINUOUS", "TOILET CLEANERS/FRESHENERS INSTANT", "TOILET CLEANING SYSTEM", "TOILET TISSUE - DRY", "TOILET TISSUE - MOIST", "TONGUE CLEANING", "TONIC WATER", "TOOTH STAIN REMOVERS", "TOOTHBRUSHES - ELECTRIC - COMPLETE PACK", "TOOTHBRUSHES - ELECTRIC - REFILL HEADS", "TOOTHBRUSHES - MANUAL", "TOOTHPASTE - FOAM/GEL/LIQUID/PASTE", "TOOTHPASTE - GUM/TABLETS/POWDER/SOLIDS", "TOPICAL ANALGESICS", "TRAVEL/MOTION SICKNESS", "URINE CONTAINERS", "VACCINES", "VACUUM CLEANER ACCESSORIES", "VEGETABLE BASED MEALS - AMBIENT", "VEGETABLES - BEANS/PODS/PULSES - AMBIENT", "VEGETABLES - BEANS/PODS/PULSES - FRESH", "VEGETABLES - BEANS/PODS/PULSES - FROZEN", "VEGETABLES - OTHER - AMBIENT", "VEGETABLES - OTHER - FRESH", "VEGETABLES - OTHER - FROZEN", "VEGETABLES - POTATOES - AMBIENT", "VEGETABLES - TOMATOES - AMBIENT", "VEGETABLES - TOMATOES - FRESH", "VEGETABLES - TOMATOES - FROZEN", "VEGETABLES WITH MEAT/FISH ADDITIVES - AMBIENT", "VEGETABLES WITH MEAT/FISH ADDITIVES - FRESH", "VEGETABLES WITH MEAT/FISH ADDITIVES - FROZEN", "VERMOUTH", "VINEGAR - AMBIENT", "VITAMIN SUPPLEMENTS", "VODKA/VODKA STYLE", "VOL AU VENT CASES - FROZEN", "WATER DISTILLED (NON DRINKABLE)", "WATER EFFERVESCENTS", "WATER FILTERS", "WAX FILTERS", "WEIGHT GAIN PRODUCTS", "WHEAT - PRODUCTS - FRESH", "WHEAT PRODUCTS - AMBIENT", "WHEAT PRODUCTS - FROZEN", "WHISKY/WHISKY STYLE", "WINE - CHAMPAGNE", "WINE - FORTIFIED", "WINE - OTHER", "WINE - SPARKLING", "WINE - SPARKLING - LOW/NON ALCOHOLIC", "WINE - SPECIALITY", "WINE - STILL - GRAPE BASED", "WINE - STILL - LOW/NON ALCOHOLIC", "WORM TREATMENTS", "WOUND DRESSING STERILE", "WOUND DRESSING STERILE WITH GAUZE PADS IN", "X-RAY CONTRAST MEDIA", "YOGURT - SPOONABLE - FRESH", "YOGURT SUBSTITUTE - SPOONABLE - FRESH", "YOGURT/YOGURT SUBSTITUTE - AMBIENT", "NON-FMCG", "UNKNOWN","BABY PERSONAL HYGIENE - UNCLASSIFIED", "BABY SPECIALISED HEALTHCARE - UNCLASSIFIED", "BABY FOOD - UNCLASSIFIED", "SPIRITS - UNCLASSIFIED", "WINES - UNCLASSIFIED", "COFFEE/COFFEE SUBSTITUTES - UNCLASSIFIED", "TEA & INFUSIONS - UNCLASSIFIED", "WATER - UNCLASSIFIED", "SPORTS/ENERGY DRINKS - UNCLASSIFIED", "DRINKS FLAVOURED RTD - UNCLASSIFIED", "SNACKS - CHIPS/CRISPS - UNCLASSIFIED", "SNACKS - UNCLASSIFIED", "EYE COSMETICS - UNCLASSIFIED", "FACE COSMETICS - UNCLASSIFIED", "LIP COSMETICS - UNCLASSIFIED", "NAIL CARE - UNCLASSIFIED", "BODY/BODY & FACE COSMETICS - UNCLASSIFIED", "NAIL POLISH & DECORATION - UNCLASSIFIED", "BREAD - AMBIENT - UNCLASSIFIED", "FILLINGS/PASTES/SPREADS - SWEET - AMBIENT - UNCLASSIFIED", "FRUIT/NUTS - AMBIENT - UNCLASSIFIED", "CHEESE - FRESH FIXED WEIGHT - UNCLASSIFIED", "DAIRY/MILK/CREAM - FRESH - UNCLASSIFIED", "DOUGH PRODUCTS - FRESH FIXED WEIGHT - UNCLASSIFIED", "FRUIT/NUTS - FRESH FIXED WEIGHT - UNCLASSIFIED", "BLADDER & GENITALS & URINARY SYSTEM & CONTRACEPTIVE PRODUCTS - UNCLASSIFIED", "CALMING & SLEEPING - UNCLASSIFIED", "COUGH COLD & OTHER RESPIRATORY REMEDIES & ACCESSORIES - UNCLASSIFIED", "DIABETES TREATMENTS/ACCESSORIES - UNCLASSIFIED", "DIAGNOSTIC TESTS - UNCLASSIFIED", "DIETARY AIDS - UNCLASSIFIED", "EAR CARE - UNCLASSIFIED", "EYE CARE - UNCLASSIFIED", "FIRST AID & MEDICAL/SURGICAL SUPPLIES - UNCLASSIFIED", "FOOT CARE/HYGIENE - UNCLASSIFIED", "HABIT TREATMENT - UNCLASSIFIED", "HEALTHCARE - UNCLASSIFIED", "MOUTH CARE - UNCLASSIFIED", "PAIN RELIEF - UNCLASSIFIED", "SKIN TREATMENTS/DERMATOLOGICS - UNCLASSIFIED", "VITAMINS & MINERALS & NUTRITIONAL SUPPLEMENTS - UNCLASSIFIED", "LAUNDRY - UNCLASSIFIED", "DISH CARE - UNCLASSIFIED", "FRESHENERS/DEODORIZERS - UNCLASSIFIED", "HOUSEHOLD CLEANERS - UNCLASSIFIED", "INSECT CONTROL - UNCLASSIFIED", "FACIAL CLEANSING & TONING - UNCLASSIFIED", "FEMININE PERSONAL HYGIENE - UNCLASSIFIED", "GENERAL PERSONAL HYGIENE - UNCLASSIFIED", "HAIR CARE - UNCLASSIFIED", "ORAL HYGIENE - UNCLASSIFIED", "SHAVING/DEPILATION FEMALE - UNCLASSIFIED", "SHAVING/DEPILATION MALE - UNCLASSIFIED", "SKIN CONDITIONING/MOISTURISING - UNCLASSIFIED", "GROOMING/PERSONAL CARE - UNCLASSIFIED", "CAT FOOD - UNCLASSIFIED", "DOG FOOD - UNCLASSIFIED", "PET FISH TREATMENTS/AQUARIUMS/ACCESSORIES - UNCLASSIFIED", "PET HYGIENE & GROOMING - UNCLASSIFIED", "TOBACCO - UNCLASSIFIED", "ELECTRONIC CIGARETTES & ACCESSORIES - UNCLASSIFIED", "TOBACCO/SNUFF - UNCLASSIFIED"
]

default_branding_repo = {
    "THEWHITECOMPANY": "THEWHITECOMPANY;THEWHITECOMPANY (THEWHITECOMPANY);THEWHITECOMPANY",
    "SMOLPRODUCTS": "SMOLPRODUCTS;SMOLPRODUCTS (SMOLPRODUCTS);SMOLPRODUCTS",
    "ZARA HOME": "ZARA HOME;ZARA HOME (ZARA HOME);ZARA HOME",
    "HM": "HM;HM (HM);HM",
    "MYMUESLI": "MYMUESLI;MYMUESLI (MYMUESLI);MYMUESLI",
    "TCHIBO": "TCHIBO;TCHIBO (TCHIBO);TCHIBO",
    "AROMAZONE": "AROMAZONE;AROMAZONE (AROMAZONE);AROMAZONE",
    "IKEA": "IKEA;IKEA (IKEA);IKEA",
    "SHEIN": "SHEIN;SHEIN;SHEIN",
    "RINGANA": "RINGANA;RINGANA (RINGANA);RINGANA",
    "BODY&FIT": "BODY&FIT;BODY&FIT (BODY&FIT);BODY&FIT",
    "LIPTON": "LIPTON;LIPTON (LIPTON);LIPTON",
    "BENEFIT": "BENEFIT;BENEFIT (BENEFIT);BENEFIT",
    "CARREFOUR": "CARREFOUR;CARREFOUR (CARREFOUR);CARREFOUR",
    "PICNIC": "PICNIC;PICNIC (PICNIC);PICNIC",
    "KIKO MILANO": "KIKO SPA;KIKO MILANO (KIKO SPA);KIKO MILANO",
    "SERA": "SERA;SERA (SERA);SERA",
    "KYLIE": "KYLIE;KYLIE (KYLIE);KYLIE",
    "ESN": "QUALITY GROUP;ESN (QUALITY GROUP);ESN",
    "AMAZON BASICS": "AMAZON BASICS;AMAZON BASICS (AMAZON BASICS);AMAZON BASICS",
    "MIGROS: FREY": "MIGROS: FREY;MIGROS: FREY (MIGROS: FREY);MIGROS: FREY",
    "MIGROS: SWISS DELICE": "MIGROS: SWISS DELICE;MIGROS: SWISS DELICE (MIGROS: SWISS DELICE);MIGROS: SWISS DELICE",
    "MIGROS other own label brands": "MIGROS other own label brands;MIGROS other own label brands (MIGROS other own label brands);MIGROS other own label brands",
    "COOP QUALITE & PRIX": "COOP QUALITE & PRIX;COOP QUALITE & PRIX (COOP QUALITE & PRIX);COOP QUALITE & PRIX",
    "PRIX GARANTIE": "PRIX GARANTIE;PRIX GARANTIE (PRIX GARANTIE);PRIX GARANTIE",
    "BEAUTY PIE": "BEAUTY PIE;BEAUTY PIE (BEAUTY PIE);BEAUTY PIE",
    "JA NATÜRLICH": "JA NATÜRLICH;JA NATÜRLICH (JA NATÜRLICH);JA NATÜRLICH",
    "DUNKIN' DONUTS": "DUNKIN' DONUTS;DUNKIN' DONUTS (DUNKIN' DONUTS);DUNKIN' DONUTS",
    "S. BUDGET": "SPAR;S. BUDGET (SPAR);S. BUDGET",
    "DIOR": "DIOR;DIOR (DIOR);DIOR",
    "HOLLANDANDBARRETT": "HOLLANDANDBARRETT;HOLLANDANDBARRETT (HOLLANDANDBARRETT);HOLLANDANDBARRETT",
    "AH": "AH;AH (AH);AH",
    "BULK": "BULK;BULK (BULK);BULK",
    "BETTY BOSSI": "BETTY BOSSI;BETTY BOSSI (BETTY BOSSI);BETTY BOSSI",
    "SAPORI D'ITALIA": "SAPORI D'ITALIA;SAPORI D'ITALIA (SAPORI D'ITALIA);SAPORI D'ITALIA",
    "WATERDROP": "WATERDROP;WATERDROP (WATERDROP);WATERDROP",
    "SODASTREAM": "SODASTREAM;SODASTREAM (SODASTREAM);SODASTREAM",
    "COLLONIL": "COLLONIL;COLLONIL (COLLONIL);COLLONIL",
    "THE PINK STUFF": "THE PINK STUFF;THE PINK STUFF (THE PINK STUFF);THE PINK STUFF",
    "BEURER": "BEURER;BEURER (BEURER);BEURER",
    "BOOSTER": "BOOSTER;BOOSTER (BOOSTER);BOOSTER",
    "ASDA": "ASDA;ASDA (ASDA);ASDA",
    "MADAUS": "VIATRIS;MADAUS (VIATRIS);MADAUS",
    "LERBOLARIO": "L'ERBOLARIO;L'ERBOLARIO;L'ERBOLARIO",
    "MYSECRETCASE": "NOT DETERMINED;MYSECRETCASE;MYSECRETCASE",
    "PASSIONEBEAUTY": "NOT DETERMINED;PASSIONE BEAUTY;PASSIONE BEAUTY",
    "YEPODA": "YEPODA;YEPODA;YEPODA",
    "KAFFEKAPSLEN": "KAFFEKAPSLEN;KAFFEKAPSLEN;KAFFEKAPSLEN",
    "NUTRI & CO": "NUTRI & CO;NUTRI & CO;NUTRI & CO",
    "TYPOLOGY": "TYPOLOGY;TYPOLOGY;TYPOLOGY",
    "CB12": "COOPER CONSUMER HEALTH;CB12 (COOPER CONSUMER HEALTH);CB12",
    "FARMINA": "RUSSO MANGIMI;FARMINA (RUSSO MANGIMI);FARMINA",
    "MIGROS": "MIGROS (PRIVATE LABEL)",
    "ESKIMO 3": "NUTRI ADVANCED;ESKIMO 3 (NUTRI ADVANCED);ESKIMO 3",
    "LA JOLIE MUSE": "TAFFETA HOME;LA JOLIE MUSE (TAFFETA HOME);LA JOLIE MUSE",
    "VETERINARY DIETS items of PURINA for PRO PLAN the branding should be": "NESTLE / PURINA;PRO PLAN;PRO PLAN VETERINARY DIETS",
    "DeBA pharma": "DE BA PHARMA;DE BA PHARMA;DE BA PHARMA",
    "Dyson": "DYSON;DYSON;DYSON",
    "DOGCHEF": "DOGCHEF;DOGCHEF;DOGCHEF",
    "MORE NUTRITION": "QUALITY GROUP;MORE NUTRITION (QUALITY GROUP);MORE NUTRITION",
    "PURITO": "HINATURE;PURITO (HINATURE);PURITO",
    "BOBBI BROWN": "BOBBI BROWN;BOBBI BROWN (BOBBI BROWN);BOBBI BROWN",
    "DR. JART+": "ESTEE LAUDER;DR. JART+ (ESTEE LAUDER);DR. JART+",
    "ARNOMED": "ARNOWA;ARNOMED (ARNOWA);ARNOMED",
    "NICOTINELL": "BOI - PERRIGO",
    "For CREALINE (AGRIAL) brand the brand has been change to": "FLORETTE (AGRIAL) Products under the Créaline banner will come under the Florette brand",
    "UMAMI": "UMAMI;UMAMI (UMAMI);UMAMI",
    "ADTAB": "ELANCO;AD TAB;AD TAB",
    "ONE TOUCH": "JOHNSON & JOHNSON;ONE TOUCH (JOHNSON & JOHNSON);ONE TOUCH.",
    "weight world": "COMFORT CLICK;WEIGHT WORLD (COMFORT CLICK);WEIGHT WORLD",
    "sculpted by aimee": "AIMEE COSMETICS;SCULPTED;SCULPTED",
    "N&D": "FARMINA PET FOODS;N&D (FARMINA PET FOODS);N&D",
    "ECOVER": "S.C. JOHNSON;ECOVER (S.C. JOHNSON);ECOVER",
    "S. BUDGET": "SPAR;S. BUDGET (SPAR);S. BUDGET"
}



def check_delivery_file(file_path, progress_bar, status_text):
    try:
        df = pd.read_excel(file_path, dtype=str).fillna("")
        errors = []
        brand_boi_map = {}
        brand_structure_map = {}
        excluded_modules = ['NON-FMCG', 'UNKNOWN']
        full_columns = list(df.columns)
        total_rows = len(df)

        product_module_map = {}
        product_brand_map = {}

        for index, row in df.iterrows():
            module_validated = row.iloc[0].strip()
            brand_validated = row.iloc[1].strip()
            product_description = row.iloc[2].strip()
            full_row_data = list(row)

            # MODULE VALIDATION
            if module_validated not in VALID_MODULES:
                errors.append([index+2, "MODULE_VALIDATED", module_validated, "Invalid module"] + full_row_data)

            if ";" in module_validated:
                errors.append([index+2, "MODULE_VALIDATED", module_validated, "Contains ';'"] + full_row_data)

            if module_validated == "" or module_validated.lower() == "query":
                errors.append([index+2, "MODULE_VALIDATED", module_validated, "Blank or Query detected in MODULE_VALIDATED"] + full_row_data)

            if any(char.islower() for char in module_validated):
                errors.append([index+2, "MODULE_VALIDATED", module_validated, "Contains lowercase letters"] + full_row_data)

            # BRAND VALIDATION
            if module_validated not in excluded_modules:
                if brand_validated == "" or brand_validated.lower() == "query":
                    errors.append([index+2, "BRAND_VALIDATED", brand_validated, "Blank or Query detected in BRAND_VALIDATED"] + full_row_data)
            else:
                if brand_validated.strip() != "":
                    errors.append([index+2, "BRAND_VALIDATED", brand_validated, f"{module_validated} should not have any BRAND"] + full_row_data)

            if "-" in brand_validated:
                errors.append([index+2, "BRAND_VALIDATED", brand_validated, "Branding contains '-'"] + full_row_data)

            if any(char.islower() for char in brand_validated):
                errors.append([index+2, "BRAND_VALIDATED", brand_validated, "Contains lowercase letters"] + full_row_data)

            if "; " in brand_validated:
                errors.append([index+2, "BRAND_VALIDATED", brand_validated, "Contains space after ';'"] + full_row_data)

            if "BRAND" in brand_validated.upper():
                errors.append([index+2, "BRAND_VALIDATED", brand_validated, "Contains the word 'BRAND'"] + full_row_data)

            # MODULE & BRAND consistency for same product
            if product_description in product_module_map and product_module_map[product_description] != module_validated:
                errors.append([index+2, "MODULE_VALIDATED", module_validated, "Different module for same product description"] + full_row_data)
            else:
                product_module_map[product_description] = module_validated

            if product_description in product_brand_map and product_brand_map[product_description] != brand_validated:
                errors.append([index+2, "BRAND_VALIDATED", brand_validated, "Different brand for same product description"] + full_row_data)
            else:
                product_brand_map[product_description] = brand_validated

            # BRAND FORMAT VALIDATION
            if not (module_validated in excluded_modules and brand_validated.strip() == ""):
                brand_parts = brand_validated.split(";")

                if len(brand_parts) != 3:
                    errors.append([index+2, "BRAND_VALIDATED", brand_validated, "Brand format incorrect (should have 3 parts)"] + full_row_data)
                else:
                    boi = brand_parts[0].strip()
                    raw_brand = brand_parts[1].strip()
                    gbe = brand_parts[2].strip()

                    clean_brand = raw_brand.replace("(", "").replace(")", "").strip()

                    if clean_brand in default_branding_repo:
                       expected_format = default_branding_repo[clean_brand]
                       if brand_validated != expected_format:
                          errors.append([index+2, "BRAND_VALIDATED", brand_validated, f"This brand is updated in repository. Kindly use: {expected_format}"] + full_row_data)


                    # Same BRAND with different BOI
                    if clean_brand in brand_boi_map and brand_boi_map[clean_brand] != boi:
                        errors.append([index+2, "BRAND_VALIDATED", brand_validated, "Same BRAND with different BOI detected"] + full_row_data)
                    else:
                        brand_boi_map[clean_brand] = boi

                    # Check for same clean brand with different raw brand structure
                    if clean_brand not in brand_structure_map:
                        brand_structure_map[clean_brand] = set()

                    if "(" in raw_brand and ")" in raw_brand:
                        brand_structure_map[clean_brand].add("with_parenthesis")
                    else:
                        brand_structure_map[clean_brand].add("normal")

                    if len(brand_structure_map[clean_brand]) > 1:
                        errors.append([index+2, "BRAND_VALIDATED", brand_validated, "Same BRAND has inconsistent formatting (with & without parentheses)"] + full_row_data)

                    if "  " in brand_validated:
                        errors.append([index+2, "BRAND_VALIDATED", brand_validated, "Contains double space"] + full_row_data)

                    if brand_validated.endswith(",") or "Not determined" in brand_validated or brand_validated.endswith(";"):
                        errors.append([index+2, "BRAND_VALIDATED", brand_validated, "Branding might be incomplete"] + full_row_data)

                    if "'" in brand_validated:
                        errors.append([index+2, "BRAND_VALIDATED", brand_validated, "Contains 's"] + full_row_data)

                    if "." in brand_validated:
                        errors.append([index+2, "BRAND_VALIDATED", brand_validated, "Brand contains '.'"] + full_row_data)

                    if "(" in raw_brand and ")" in raw_brand:
                        boi_inside_parenthesis = re.search(r"\((.*?)\)", raw_brand)
                        if boi_inside_parenthesis and boi_inside_parenthesis.group(1) != boi:
                            errors.append([index+2, "BRAND_VALIDATED", brand_validated, "BOI contains parentheses"] + full_row_data)

                    if "(" in gbe or ")" in gbe:
                        errors.append([index+2, "BRAND_VALIDATED", brand_validated, "Global Brand Extension contains parentheses"] + full_row_data)

            # ✅ Update progress
            progress = int((index + 1) / total_rows * 100)
            progress_bar.progress(progress)
            status_text.text(f"Processing row {index + 1} of {total_rows}... {progress}%")
            time.sleep(0.01)

        # Final update
        progress_bar.progress(100)
        status_text.text("Processing complete! ✅ 100%")

        if errors:
            error_columns = ["Row", "Column", "Value", "Error"] + full_columns
            error_df = pd.DataFrame(errors, columns=error_columns)
            output = io.BytesIO()
            with pd.ExcelWriter(output, engine="xlsxwriter") as writer:
                error_df.to_excel(writer, index=False)
            return output.getvalue(), "Errors found! Download the error report."
        else:
            return None, "No errors found! File is clean."

    except Exception as e:
        return None, f"Error processing file: {str(e)}"



# Streamlit UI
st.title("FileSure - Validator")
st.subheader("Developed by Burhanuddin Adenwala")

uploaded_file = st.file_uploader("Upload your delivery file (.xlsx)", type=["xlsx"])

if uploaded_file:
    progress_bar = st.progress(0)
    status_text = st.empty()

    with st.spinner("Processing file..."):
        error_file, result_message = check_delivery_file(uploaded_file, progress_bar, status_text)

    st.write(result_message)

    if error_file:
        st.download_button(
            label="Download Error Report",
            data=error_file,
            file_name="Error_Report.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )
